ALTER TABLE kpi_daily
ADD COLUMN IF NOT EXISTS full_bins_count INT NOT NULL DEFAULT 0;

ALTER TABLE kpi_daily
ADD COLUMN IF NOT EXISTS open_alerts_count INT NOT NULL DEFAULT 0;

ALTER TABLE kpi_daily
ADD COLUMN IF NOT EXISTS active_trucks_count INT NOT NULL DEFAULT 0;

ALTER TABLE kpi_daily
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();