ALTER TABLE users
ADD COLUMN IF NOT EXISTS first_name VARCHAR(100);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS last_name VARCHAR(100);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS job_title VARCHAR(120);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS organization VARCHAR(150);