ALTER TABLE missions
ADD COLUMN IF NOT EXISTS truck_id BIGINT REFERENCES trucks(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS depot_id BIGINT,
ADD COLUMN IF NOT EXISTS estimated_distance_km NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS actual_distance_km NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS estimated_duration_min INT,
ADD COLUMN IF NOT EXISTS actual_duration_min INT,
ADD COLUMN IF NOT EXISTS estimated_fuel_liters NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS actual_fuel_liters NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS replanned_count INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS mission_status_detail VARCHAR(30);