ALTER TABLE mission_bins
ADD COLUMN IF NOT EXISTS assignment_status VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
ADD COLUMN IF NOT EXISTS reassigned_from_truck_id BIGINT REFERENCES trucks(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS reassigned_to_truck_id BIGINT REFERENCES trucks(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS planned_arrival TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS actual_arrival TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS skipped_reason VARCHAR(50);