CREATE TABLE IF NOT EXISTS fuel_stations (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    fuel_type VARCHAR(20) NOT NULL CHECK (fuel_type IN ('DIESEL','ESSENCE','ELECTRIC','HYBRID')),
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);